"""Write the VIC 5 classic-driver global parameter file.

Generated rather than hand-written so paths, dates and the forcing column order
come from configs/config.py and cannot drift out of step with the files the
other scripts produce.  A global parameter file that disagrees with the forcing
column order does not error -- VIC reads temperature as precipitation and
produces plausible nonsense.

Model configuration and why:

  *_STEPS_PER_DAY   4     Forced, not chosen.  VIC 5 requires >= 4 sub-daily
                          snow steps, FORCE must equal SNOW, and with sub-daily
                          forcing MODEL must equal FORCE.  Output is aggregated
                          back to daily with AGGFREQ NDAYS 1.
  FULL_ENERGY  FALSE      Water balance only; no surface energy balance.  With
                          no snow and no frozen ground there is nothing for it
                          to resolve here.
  FROZEN_SOIL  FALSE      Minimum January temperature over the record is ~2 C
                          at 2 m; soil never freezes.
  SNOW_BAND    1          Relief within a 0.25 deg cell averages 360 m and the
                          basin never sees snow, so elevation bands would
                          partition a process that does not occur.
  BASEFLOW     ARNO       Matches the Ds/Dsmax/Ws/c parameterisation written by
                          build_soil_params.py.

FORCE_TYPE order MUST match the column order written by build_forcing.py.
VIC 5 removed MTCLIM, so all seven forcings are mandatory -- there is no
TMAX/TMIN input and nothing is derived internally.

Run:  python hydrology/vic/build_global_param.py
Out:  data/processed/vic/global_param.txt
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))
from configs import config as C

# VIC's global-parameter parser splits on whitespace, so ANY path containing a
# space is silently truncated -- this project lives under "untitled folder",
# and VIC dutifully tried to write its log to ".../Desktop/untitledvic.log".
# It does not error; it just uses the wrong path.  A space-free symlink is the
# only fix short of moving the project.
_REAL = C.PROCESSED / "vic"


def _safe_dir(real: Path) -> Path:
    if " " not in str(real):
        return real
    link = Path.home() / ".vic_mahanadi"
    if link.is_symlink() and link.resolve() == real.resolve():
        return link
    if link.exists() or link.is_symlink():
        link.unlink()
    real.mkdir(parents=True, exist_ok=True)
    link.symlink_to(real)
    return link


VICDIR = _safe_dir(_REAL)
OUT = _REAL / "global_param.txt"

# Must match build_forcing.py exactly.  Order is the file's column order.
FORCE_COLUMNS = ["PREC", "AIR_TEMP", "SWDOWN", "LWDOWN", "PRESSURE", "VP", "WIND"]

# Fluxes needed to drive routing, plus the state variables worth inspecting.
OUTVARS = [
    "OUT_RUNOFF",       # surface runoff, mm  -> RVIC
    "OUT_BASEFLOW",     # baseflow, mm        -> RVIC
    "OUT_EVAP",         # total ET, mm
    "OUT_PREC",         # precipitation as VIC saw it (closes the balance)
    "OUT_SOIL_MOIST",   # per layer, mm       -> compare against ERA5 swvl
    "OUT_SWE",          # expected ~0; a non-zero value means something is wrong
]


def main() -> None:
    VICDIR.mkdir(parents=True, exist_ok=True)
    (VICDIR / "output").mkdir(exist_ok=True)
    (VICDIR / "logs").mkdir(exist_ok=True)

    # Dates come from the forcing itself.  Declaring them separately is how a
    # global parameter file ends up asking VIC to read past the end of the
    # forcing, which it reports as a confusing read error rather than a date
    # mismatch.
    import pandas as pd
    fnc = VICDIR / "forcing_daily.nc"
    if fnc.exists():
        import xarray as xr
        t = pd.DatetimeIndex(xr.open_dataset(fnc).time.values)
        start, end = t[0], t[-1]
    else:
        start = pd.Timestamp(f"{C.YEAR_MIN - 1}-01-01")
        end = pd.Timestamp(f"{C.YEAR_MAX}-12-30 18:00")

    L = []
    add = L.append

    add("# VIC 5 classic driver -- Mahanadi above Hirakud")
    add("# GENERATED by hydrology/vic/build_global_param.py -- do not hand-edit;")
    add("# edit the generator so the forcing column order stays in step.")
    add("")
    add("#--- simulation period ------------------------------------------------")
    add(f"STARTYEAR   {start.year}")
    add(f"STARTMONTH  {start.month}")
    add(f"STARTDAY    {start.day}")
    add("STARTSEC    0")
    add(f"ENDYEAR     {end.year}")
    add(f"ENDMONTH    {end.month}")
    add(f"ENDDAY      {end.day}")
    add("CALENDAR    PROLEPTIC_GREGORIAN")
    add("")
    add("#--- time stepping ----------------------------------------------------")
    # 6-hourly throughout, and none of it is a free choice:
    #   snow_steps_per_day >= 4        VIC 5 refuses fewer sub-daily steps even
    #                                  with no snow -- the snow model always
    #                                  runs, it just produces zero.
    #   FORCE == SNOW                  enforced in get_global_param.c
    #   MODEL == FORCE (sub-daily)     enforced in read_atmos_data.c: "the model
    #                                  must be run at the same time step as the
    #                                  forcing data".  So a daily water balance
    #                                  driven by 6-hourly forcing is NOT
    #                                  possible, despite model_steps_per_day==1
    #                                  being exempted from the SNOW check.
    # 6-hourly is the native resolution of the met/rad/sp ERA5 streams, so
    # nothing is discarded; output is aggregated back to daily via AGGFREQ.
    add("MODEL_STEPS_PER_DAY   4")
    add("SNOW_STEPS_PER_DAY    4")
    add("RUNOFF_STEPS_PER_DAY  4")
    # VIC enforces FORCE_STEPS_PER_DAY == SNOW_STEPS_PER_DAY.
    add("FORCE_STEPS_PER_DAY   4")
    add("")
    add("#--- model physics ----------------------------------------------------")
    add("FULL_ENERGY  FALSE")
    add("FROZEN_SOIL  FALSE")
    # Water-balance mode (FULL_ENERGY and FROZEN_SOIL both FALSE) requires
    # QUICK_FLUX TRUE -- VIC refuses the combination otherwise.
    add("QUICK_FLUX   TRUE")
    add("IMPLICIT     FALSE")
    add("EXP_TRANS    FALSE")
    add("SNOW_BAND    1")
    add("COMPUTE_TREELINE FALSE")
    add("CORRPREC     FALSE")
    add("CLOSE_ENERGY FALSE")
    add("CONTINUEONERROR FALSE")
    add("")
    add("#--- forcing ----------------------------------------------------------")
    add(f"FORCING1     {VICDIR / 'forcings' / 'data_'}")
    add("FORCE_FORMAT ASCII")
    for name in FORCE_COLUMNS:
        add(f"FORCE_TYPE   {name}")
    add(f"FORCEYEAR    {start.year}")
    add(f"FORCEMONTH   {start.month}")
    add(f"FORCEDAY     {start.day}")
    add("FORCESEC     0")
    # Filenames are written as data_<lat>_<lon> with four decimals; VIC rebuilds
    # them from GRID_DECIMAL, so a mismatch here means "file not found".
    add("GRID_DECIMAL 4")
    add("WIND_H       10.0")
    add("")
    add("#--- parameters -------------------------------------------------------")
    add(f"SOIL         {VICDIR / 'soil_param.txt'}")
    add("BASEFLOW     ARNO")
    add("JULY_TAVG_SUPPLIED FALSE")
    add("ORGANIC_FRACT      FALSE")
    add("NLAYER       3")
    add("NODES        3")
    add("")
    add(f"VEGLIB       {VICDIR / 'veg_lib.txt'}")
    add("VEGLIB_PHOTO FALSE")
    add("VEGLIB_FCAN  FALSE")
    add(f"VEGPARAM     {VICDIR / 'veg_param.txt'}")
    add("ROOT_ZONES   3")
    # Our veg_param carries fractions and roots only; LAI and albedo come from
    # the library, where the monsoon phenology was set.
    add("VEGPARAM_LAI FALSE")
    add("VEGPARAM_ALB FALSE")
    add("VEGPARAM_FCAN FALSE")
    add("LAI_SRC      FROM_VEGLIB")
    add("ALB_SRC      FROM_VEGLIB")
    add("FCAN_SRC     FROM_DEFAULT")
    add("")
    add("#--- output -----------------------------------------------------------")
    add(f"RESULT_DIR   {VICDIR / 'output'}/")
    add(f"LOG_DIR      {VICDIR / 'logs'}/")
    # Order matters: OUTFILE opens an output-file block, and OUT_FORMAT,
    # COMPRESS, AGGFREQ and OUTVAR all attach to the block above them.  Putting
    # OUT_FORMAT first is an error, not a warning.
    add(f"OUTFILE      fluxes")
    add("OUT_FORMAT   ASCII")
    add("COMPRESS     FALSE")
    add("AGGFREQ      NDAYS 1")
    for v in OUTVARS:
        add(f"OUTVAR       {v}")
    add("")

    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT}")
    if VICDIR != _REAL:
        print(f"  paths inside it go via {VICDIR} (space-free symlink)")

    # ---- checks that would otherwise surface as a confusing VIC abort
    print("\n=== checks ===")
    ok = True
    for label, p in [("soil", VICDIR / "soil_param.txt"),
                     ("veglib", VICDIR / "veg_lib.txt"),
                     ("vegparam", VICDIR / "veg_param.txt")]:
        e = p.exists()
        print(f"  {label:9s} {'OK ' if e else 'MISSING'}  {p.name}")
        ok &= e

    fdir = VICDIR / "forcings"
    n = len(list(fdir.glob("data_*"))) if fdir.exists() else 0
    print(f"  forcings  {n} file(s)" + ("" if n else "  <- run build_forcing.py"))
    if n:
        sample = sorted(fdir.glob("data_*"))[0]
        ncol = len(sample.read_text().splitlines()[0].split())
        print(f"  columns   {ncol} in {sample.name}  "
              f"{'OK' if ncol == len(FORCE_COLUMNS) else f'<- expected {len(FORCE_COLUMNS)}'}")
        ok &= ncol == len(FORCE_COLUMNS)
    else:
        ok = False

    print(f"\n{'READY' if ok else 'NOT READY'} -- run with:")
    print(f"  hydrology/vic/VIC/vic/drivers/classic/vic_classic.exe -g {OUT}")
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
